shell = "zsh"

## Templates
[templates]
# PATHに追加するテンプレート
path = 'export PATH="{{ dir }}:$PATH"'
# fpathに追加するテンプレート
fpath = 'fpath=({{ dir }} $fpath)'
# 即時実行するテンプレート
source = '{{ hooks?.pre | nl }}{% for file in files %}source "{{ file }}"{% endfor %}{{ hooks?.post | nl }}'
# 遅延実行するテンプレート
defer = '{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source "{{ file }}"\n{% endfor %}{{ hooks?.post | nl }}'

# -----------------------------------------------------------------------------
## Core Plugins
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-256color]
github = "chrissicool/zsh-256color"

[plugins.jq-zsh-plugin]
github = "reegnz/jq-zsh-plugin"

[plugins.cd-gitroot]
github = "mollifier/cd-gitroot"

[plugins.anyframe]
github = "mollifier/anyframe"

## Git Extensions
[plugins.git-recall]
github = "Fakerr/git-recall"
apply = ["path"]

[plugins.git-open]
github = "paulirish/git-open"
apply = ["path"]

[plugins.git-recent]
github = "paulirish/git-recent"
apply = ["path"]

[plugins.git-my]
github = "davidosomething/git-my"
apply = ["path"]

[plugins.git-now]
github = "iwata/git-now"
apply = ["path"]

[plugins.git-extras]
github = "tj/git-extras"
# git-extrasは本来make installが必要ですが、binをPATHに通すだけでも多くの機能が動きます
dir = "bin"
apply = ["path"]

# Shell Settings
[plugins.zsh-local-immediate]
inline = '''
source "${_ZDOTDIR}/env.zsh"
source "${_ZDOTDIR}/prompt.zsh"
'''

[plugins.zsh-local-settings]
inline = '''
source "${_ZDOTDIR}/history.zsh"
source "${_ZDOTDIR}/bindkeys.zsh"
source "${_ZDOTDIR}/alias.zsh"
'''

[plugins.zsh-local-ssh-agent]
inline = '[ -e ${HOME}/.ssh/agent-env ] && source ${HOME}/.ssh/agent-env'

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["fpath"]

[plugins.zsh-local-functions]
inline = '''
fpath=(${_ZDOTDIR}/functions $fpath)
autoload -Uz ${_ZDOTDIR}/functions/*(N:t)
'''

[plugins.plugins-init-tools]
inline = '''
local comp_dir="${XDG_CACHE_HOME}/zsh/completions"
[[ ! -d "$comp_dir" ]] && mkdir -p "$comp_dir"
fpath=($comp_dir $fpath)

source ${_ZDOTDIR}/completions.zsh
source "${_ZDOTDIR}/init_tools.zsh"
'''

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]