# ~/.config/starship.toml
"$schema" = 'https://starship.rs/config-schema.json'

# 改行を入れてプロンプトを読みやすくする
add_newline = true

# プロンプトのフォーマット（表示順序）
format = """
$os$directory$git_branch$git_status$rust$node$python$lua$fill$cmd_duration$line_break$character
"""

[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bold ppurple"

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[fill]
symbol = " " # 右側に情報を寄せるための空白埋め

[cmd_duration]
min_time = 500
format = "took [$duration]($style) "
style = "yellow"

[os]
disabled = false
style = "bold white"

[os.symbols]
Macos = " "
Ubuntu = " "
Arch = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
